config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  resources :coins
  resources :home

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new edit update create ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Deletado com Sucesso!." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
    
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   
    def locale(locale)
        I18n.locale == :en ? "Inglês" : "Portugês-Br"
    end
   
    def date_br(date_us)
        date_us.strftime("%d/%m/%Y")
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :url_image %>
    <%= form.text_field :url_image %>
    <td> <%#= image_tag coin.url_image, width: 50, height: 50 %> </td>
  </div>

  <div class="field">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blank: "Selecione..." }) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1>Editing Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>TABELA</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th>Url image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td> <%= image_tag coin.url_image, size: "50x50" %> </td>
        <td><%= link_to 'Vizualizar', coin %></td>
        <td><%= link_to 'Editar', edit_coin_path(coin) %></td>
        <td><%= link_to 'Apagar', coin, method: :delete, data: { confirm: 'Você tem certeza que deseja deletar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Item', new_coin_path %>
<td> | </td>
<%= link_to 'Back to Home', home_index_path %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Url image:</strong>
  <%= image_tag @coin.url_image, size: "50x50" %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>

app/views/home/_menu.html.erb
<ul>
    <li>
        <%= link_to "Tabela de Moedas", coins_path %>
    </li>

    <li>
        <%= link_to "Tabela de mineração", mining_types_path %>
    </li>

</ul>

app/views/home/_rodape.html.erb
<p>
    ISSO É UM ESTUDO DE CASO 
</p>

app/views/home/index.html.erb
<h1>Isso é um TESTE<h1>

<p>
    Vamos testar? O idioma usado na aplicação é: <strong><%= locale(I18n.locale)%></strong>
</p>

<%= render "menu" %>

<p> 
    Teste realizado no dia: <%= Date.today %>
</p>

<%= render "rodape" %>




app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aplicacao</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p>Testando o Layout</p>
 <%= image_tag "https://i.redd.it/siztzgivq7c61.jpg", size: "375x125" %>
    
    <%= yield %>

  <p> Teste de rodape</p>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<h1>Editing Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Show', @mining_type %> |
<%= link_to 'Back', mining_types_path %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining Types</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Acronym</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to 'Show', mining_type %></td>
        <td><%= link_to 'Edit', edit_mining_type_path(mining_type) %></td>
        <td><%= link_to 'Destroy', mining_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mining Type', new_mining_type_path %>
<td> | </td>
<%= link_to 'Back to Home', home_index_path %>

app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to 'Edit', edit_mining_type_path(@mining_type) %> |
<%= link_to 'Back', mining_types_path %>